version: "3.1"
services:

  db_local:
    image: postgres:15
    container_name: postgres_local
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - local-db-pgdata:/var/lib/postgresql/data/pgdata

volumes:
  local-db-pgdata:
